---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      name: jenkins
  template:
    metadata:
      name: jenkins-pod
      labels:
        name: jenkins
    spec:
      containers:
        - name: jenkins
          image: jenkins/jenkins
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 20m
---
apiVersion: v1
kind: Service
metadata:
  name: jenkins-service
  labels:
    name: jenkins
spec:
  ports:
    - port: 8080
  selector:
     name: jenkins

