---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    auhtor: intelliqit
    type: db
spec:
  containers:
    - name: mydb
      image: mysql:5
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-password
              key: password