---
apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    name: postgres
spec:
  containers:
    - name: psotgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_PASSWORD
          value: intelliqit
        - name: POSTGRES_USER
          value: myuser
        - name: POSTGRES_DB
          value: mydb
...